//GET request for person with id 5.
GET https://rocky-coast-07710.herokuapp.com/api/persons/5

###
//GET request for person with id 7. Hardcoded array does not contain one by default.
GET https://rocky-coast-07710.herokuapp.com/api/persons/7

###
//DELETE person with id 3.
DELETE https://rocky-coast-07710.herokuapp.com/api/persons/3

###
//CREATE a new person with its number.
POST https://rocky-coast-07710.herokuapp.com/api/persons
Content-Type: application/json

{
    "name": "Restful Joe",
    "number": "010-005-9988"
}
###
//Attempt to create new person failed because of property missing
POST https://rocky-coast-07710.herokuapp.com/api/persons
Content-Type: application/json

{
    "number": "010-005-9988"
}
###
//Attempt to create new person failed because this name already exists in phonebook
POST https://rocky-coast-07710.herokuapp.com/api/persons
Content-Type: application/json

{
    "name":"Arto Hellas",
    "number": "010-005-9988"
}